MainApp/MainApp/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from account.views import redirect_based_on_user_type
from django.urls import include, path
from timesheet.views import (
    my_view
)
from account.views import(

    consultant_view,manager_view,financial_view,redirect_based_on_user_type,
    view_past_timesheets,view_timesheets
   
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', my_view,name="home"),
    path('account/', include('account.urls', namespace='account')),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='login'),
    path('timesheet/', include('timesheet.urls', namespace='timesheet')),
    path('redirect/', redirect_based_on_user_type, name='redirect_user_type'),
    path('consultant/', consultant_view, name='consultant'),
    path('financial/', financial_view, name='financial'),
    path('manager/', manager_view, name='manager'),
    path('past-timesheets/', view_past_timesheets, name='view_past_timesheets'),
    path('timesheets/', view_timesheets, name='view_timesheets'),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    

    
    

    
    
    
]

MainApp/account/urls.py
from django.urls import path
from .views import consultant_view,manager_view,financial_view,redirect_based_on_user_type,view_past_timesheets,view_timesheets,update_timesheet_entry
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('portal/', views.portal_view, name='portal'),
    path('logout/', views.logout_redirect, name='logout'),
    path('redirect/', redirect_based_on_user_type, name='redirect_user_type'),
    path('consultant/', consultant_view, name='consultant'),
    path('financial/', financial_view, name='financial'),
    path('manager/', manager_view, name='manager'),
    path('view_today_timesheet/', views.view_today_timesheet, name='timesheetview'),
    path('past-timesheets/', view_past_timesheets, name='view_past_timesheets'),
    path('timesheets/', view_timesheets, name='view_timesheets'),
    path('timesheets/update_entry/', update_timesheet_entry, name='update_timesheet_entry'),
    
    
]

MainApp/notifications/urls.py
from django.urls import path

from .views import view_notifications

app_name = 'notifications'

urlpatterns = [
    
    path('notifications/', view_notifications, name='notifications'),
    
    
]

MainApp/MainApp/templates/ConsultantT.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/consultantT.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    
    
    <title>OurTime Portal</title>
</head>
<header>
        <h2 class="header1">Work Force Management</h2>
</header>
<nav class="navbar">
  <ul class="navbar-nav">
      <li class="logo">
          <a href="#" class="nav-link">
              <span class="link-text logo-text">OurTime</span>
              <svg aria-hidden="true" focusable="false" data-prefix="fad" data-icon="angle-double-right" role="img"
                  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"
                  class="svg-inline--fa fa-angle-double-right fa-w-14 fa-5x">
                  <g class="fa-group">
                      <path fill="currentColor"
                          d="M224 273L88.37 409a23.78 23.78 0 0 1-33.8 0L32 386.36a23.94 23.94 0 0 1 0-33.89l96.13-96.37L32 159.73a23.94 23.94 0 0 1 0-33.89l22.44-22.79a23.78 23.78 0 0 1 33.8 0L223.88 239a23.94 23.94 0 0 1 .1 34z"
                          class="fa-secondary"></path>
                      <path fill="currentColor"
                          d="M415.89 273L280.34 409a23.77 23.77 0 0 1-33.79 0L224 386.26a23.94 23.94 0 0 1 0-33.89L320.11 256l-96-96.47a23.94 23.94 0 0 1 0-33.89l22.52-22.59a23.77 23.77 0 0 1 33.79 0L416 239a24 24 0 0 1-.11 34z"
                          class="fa-primary"></path>
                  </g>
              </svg>
          </a>
      </li>

      <li class="nav-item">
          <a href="{% url 'account:consultant' %}" class="nav-link">
              <span class="link-text">Home</span>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                  <path
                      d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z" />
              </svg>
          </a>
      </li>

      <li class="nav-item">
          <a href="{% url 'account:timesheetview' %}" class="nav-link">
              <span class="link-text">View Timesheet</span>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                  <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                  <path
                      d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z" />
              </svg>
          </a>
      </li>

      <li class="nav-item">
          <a href="{% url 'account:view_past_timesheets' %}" class="nav-link">
              <span class="link-text">TimeSheet History</span>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                  <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                  <path
                      d="M75 75L41 41C25.9 25.9 0 36.6 0 57.9V168c0 13.3 10.7 24 24 24H134.1c21.4 0 32.1-25.9 17-41l-30.8-30.8C155 85.5 203 64 256 64c106 0 192 86 192 192s-86 192-192 192c-40.8 0-78.6-12.7-109.7-34.4c-14.5-10.1-34.4-6.6-44.6 7.9s-6.6 34.4 7.9 44.6C151.2 495 201.7 512 256 512c141.4 0 256-114.6 256-256S397.4 0 256 0C185.3 0 121.3 28.7 75 75zm181 53c-13.3 0-24 10.7-24 24V256c0 6.4 2.5 12.5 7 17l72 72c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-65-65V152c0-13.3-10.7-24-24-24z" />
              </svg>
          </a>
      </li>

  </ul>
</nav>
<body>
  <div id="MasterContainer">
    <div id="container">
      <div id="header">
        <div id="monthDisplay"></div>
        <div>
          <button id="toggleBtn" onclick="toggleClock()">Clock In</button>
          <button id="pauseBtn" onclick="pauseTimer()">Clock Out</button>
          <button id="backButton">Back</button>
          <button id="nextButton">Next</button>
          <form action="{% url 'notifications:notifications' %}" method="get">
            <button type="submit" class="post">
                <i class="fas fa-envelope"></i>
            </button>
        </form>
        </div>
      </div>

      <style>
        #messageBox {
          display: none;
          width: 600px;
          height: 300px;
          background-color: grey;
          color: white;
          text-align: center;
          position: fixed;
          top: 50%;
          left: 50%;
          transform: translate(-50%, -50%);
          box-sizing: border-box;
          padding: 20px;
        }

        #closeButton {
          display: block;
          margin: 20px auto 0;
          padding: 5px 10px;
          cursor: pointer;
          background-color: darkred;
          color: white;
          border: none;
        }

        #messageBoxContent {
          height: calc(100% - 40px);
          overflow: auto;
          margin-bottom: 20px;
          text-align: left;
        }

        .message {
          border-bottom: 1pt solid white;
        }
        .show {
          display: block;
        }
        .hide {
          display: none;
        }
      </style>

<div id="messageBox" style="display:none;">
  <div id="messageBoxContent">
      <div id="notifications">
          <!-- Notifications will be inserted here by the JavaScript -->
      </div>
  </div>
  <button id="closeButton">Close</button>
</div>


      <script>
      document.addEventListener('DOMContentLoaded', (event) => {
    const form = document.querySelector('form');
    const messageBox = document.getElementById('messageBox');
    const closeButton = document.getElementById('closeButton');
    const notificationsContainer = document.getElementById('notifications');

    form.addEventListener('submit', function (e) {
        e.preventDefault(); // Prevent the form from submitting traditionally

        // Use Fetch API to send an AJAX GET request to the server
        fetch(this.action, {
            method: 'GET',
            headers: {
                'X-Requested-With': 'XMLHttpRequest', // Important for Django to recognize AJAX request
            },
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok ' + response.statusText);
            }
            return response.json();
        })
        .then(notifications => {
            notificationsContainer.innerHTML = ''; // Clear existing notifications

            // Check if there are no notifications
            if (notifications.length === 0) {
                notificationsContainer.innerHTML = '<div class="message">No notifications.</div>';
            } else {
                // Add each notification to the message box
                notifications.forEach(notification => {
                    const notificationElement = document.createElement('div');
                    notificationElement.className = 'message';
                    notificationElement.innerHTML = `
                        <p>${notification.message}</p>
                        <small>Received on: ${new Date(notification.created_at).toLocaleString()}</small>
                    `;
                    notificationsContainer.appendChild(notificationElement);
                });
            }

            // Show the message box
            messageBox.style.display = 'block';
        })
        .catch(error => {
            console.error('Error:', error);
            notificationsContainer.innerHTML = '<div class="message">Error loading messages.</div>';
        });
    });

    closeButton.addEventListener('click', function () {
        messageBox.style.display = 'none';
    });
});

      </script>

      <div id="weekdays">
        <div>Sunday</div>
        <div>Monday</div>
        <div>Tuesday</div>
        <div>Wednesday</div>
        <div>Thursday</div>
        <div>Friday</div>
        <div>Saturday</div>
      </div>

      <div id="calendar"></div>
    </div>

    <div id="newEventModal">
      <h2>New Event</h2>

      <input id="eventTitleInput" placeholder="Event Title" />

      <button id="saveButton">Save</button>
      <button id="cancelButton">Cancel</button>
    </div>

    <div id="deleteEventModal">
      <h2>Event</h2>

      <p id="eventText"></p>

      <button id="deleteButton">Delete</button>
      <button id="closeButton">Close</button>
    </div>

    <div id="modalBackDrop"></div>

    <script src="{% static 'Javascrpt/consultantT.js' %}"></script>
  </div>
</body>
</html>

MainApp/MainApp/templates/login1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/login1.css' %}">

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login Page</title>
</head>
<body>

<div class="flex-container">
    <h1><img src="{% static '/Images/logo3.jpg' %}" alt="My Logo"></h1>
    <div class="form-container">
        <form action="{% url 'account:login_view' %}" method="post" id="login-form">
            {% csrf_token %}
            <h2>Login to your account</h2>
            <div class="input-container">
                <label for="email">Email</label>
                <input type="email" required placeholder="example@gmail.com" name="loginUser">
            </div>
            <div class="input-container">
                <label for="password">Password</label>
                <input type="password" required id="password" placeholder="Enter your password" name="loginPassword">
                <i class="fas fa-eye" id="togglePassword"></i>
            </div>
            <div class="forgot-container">
                <a href="change.html">Forgot?</a>
            </div>
            <div class="button-container">
                <button type="submit">Login now</button>
                {% if error %}
                <div style="color: rgb(12, 54, 107);">{{ error }}</div>
                {% endif %}
            </div>
        </form>
    </div>

    
</div>
<script>
    const togglePassword = document.querySelector('#togglePassword');
    const password = document.querySelector('#password');

    togglePassword.addEventListener('click', function (e) {
        const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
        password.setAttribute('type', type);
        
        this.classList.toggle('fa-eye');
        this.classList.toggle('fa-eye-slash');
    });

    

</script>
</body>
</html>

MainApp/MainApp/templates/timesheethistory.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/timesheethistory.css' %}">
    <title>TimeSheet History</title>
</head>
<header>
    <h2 class="header1">Time Sheet History</h2>
</header>
<nav class="navbar">
    <ul class="navbar-nav">
        <li class="logo">
            <a href="#" class="nav-link">
                <span class="link-text logo-text">OurTime</span>
                <svg aria-hidden="true" focusable="false" data-prefix="fad" data-icon="angle-double-right" role="img"
                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"
                    class="svg-inline--fa fa-angle-double-right fa-w-14 fa-5x">
                    <g class="fa-group">
                        <path fill="currentColor"
                            d="M224 273L88.37 409a23.78 23.78 0 0 1-33.8 0L32 386.36a23.94 23.94 0 0 1 0-33.89l96.13-96.37L32 159.73a23.94 23.94 0 0 1 0-33.89l22.44-22.79a23.78 23.78 0 0 1 33.8 0L223.88 239a23.94 23.94 0 0 1 .1 34z"
                            class="fa-secondary"></path>
                        <path fill="currentColor"
                            d="M415.89 273L280.34 409a23.77 23.77 0 0 1-33.79 0L224 386.26a23.94 23.94 0 0 1 0-33.89L320.11 256l-96-96.47a23.94 23.94 0 0 1 0-33.89l22.52-22.59a23.77 23.77 0 0 1 33.79 0L416 239a24 24 0 0 1-.11 34z"
                            class="fa-primary"></path>
                    </g>
                </svg>
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'account:consultant' %}" class="nav-link">
                <span class="link-text">Home</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                    <path
                        d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z" />
                </svg>
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'account:timesheetview' %}" class="nav-link">
                <span class="link-text">View Timesheet</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                    <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                    <path
                        d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z" />
                </svg>
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'account:view_past_timesheets' %}" class="nav-link">
                <span class="link-text">TimeSheet History</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                    <path
                        d="M75 75L41 41C25.9 25.9 0 36.6 0 57.9V168c0 13.3 10.7 24 24 24H134.1c21.4 0 32.1-25.9 17-41l-30.8-30.8C155 85.5 203 64 256 64c106 0 192 86 192 192s-86 192-192 192c-40.8 0-78.6-12.7-109.7-34.4c-14.5-10.1-34.4-6.6-44.6 7.9s-6.6 34.4 7.9 44.6C151.2 495 201.7 512 256 512c141.4 0 256-114.6 256-256S397.4 0 256 0C185.3 0 121.3 28.7 75 75zm181 53c-13.3 0-24 10.7-24 24V256c0 6.4 2.5 12.5 7 17l72 72c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-65-65V152c0-13.3-10.7-24-24-24z" />
                </svg>
            </a>
        </li>

    </ul>
</nav>
<body>
    {% for timesheet in past_timesheets %}
    <div id="historycontainer">
        <h3>{{ timesheet.date }}</h3>
        <p>Hours: {{ timesheet.total_hours|floatformat:2 }}</p>
        <p>Status: {{ timesheet.status }}</p>
    </div>
{% empty %}
    <div id="historycontainer">
        <h3>No Timesheet History</h3>
        <p>Hours: N/A</p>
        <p>Status: N/A</p>
    </div>
{% endfor %}
</body>
</html>

MainApp/MainApp/templates/viewTimeSheet.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/viewtimesheet.css' %}">
    <title>OurTime Portal</title>
</head>
<header>
    <h2 class="header1">View Time Sheet</h2>
</header>
<nav class="navbar">
    <ul class="navbar-nav">
        <li class="logo">
            <a href="#" class="nav-link">
                <span class="link-text logo-text">OurTime</span>
                <svg aria-hidden="true" focusable="false" data-prefix="fad" data-icon="angle-double-right" role="img"
                    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"
                    class="svg-inline--fa fa-angle-double-right fa-w-14 fa-5x">
                    <g class="fa-group">
                        <path fill="currentColor"
                            d="M224 273L88.37 409a23.78 23.78 0 0 1-33.8 0L32 386.36a23.94 23.94 0 0 1 0-33.89l96.13-96.37L32 159.73a23.94 23.94 0 0 1 0-33.89l22.44-22.79a23.78 23.78 0 0 1 33.8 0L223.88 239a23.94 23.94 0 0 1 .1 34z"
                            class="fa-secondary"></path>
                        <path fill="currentColor"
                            d="M415.89 273L280.34 409a23.77 23.77 0 0 1-33.79 0L224 386.26a23.94 23.94 0 0 1 0-33.89L320.11 256l-96-96.47a23.94 23.94 0 0 1 0-33.89l22.52-22.59a23.77 23.77 0 0 1 33.79 0L416 239a24 24 0 0 1-.11 34z"
                            class="fa-primary"></path>
                    </g>
                </svg>
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'account:consultant' %}" class="nav-link">
                <span class="link-text">Home</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                    <path
                        d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z" />
                </svg>
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'account:timesheetview' %}" class="nav-link">
                <span class="link-text">View Timesheet</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                    <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                    <path
                        d="M288 32c-80.8 0-145.5 36.8-192.6 80.6C48.6 156 17.3 208 2.5 243.7c-3.3 7.9-3.3 16.7 0 24.6C17.3 304 48.6 356 95.4 399.4C142.5 443.2 207.2 480 288 480s145.5-36.8 192.6-80.6c46.8-43.5 78.1-95.4 93-131.1c3.3-7.9 3.3-16.7 0-24.6c-14.9-35.7-46.2-87.7-93-131.1C433.5 68.8 368.8 32 288 32zM144 256a144 144 0 1 1 288 0 144 144 0 1 1 -288 0zm144-64c0 35.3-28.7 64-64 64c-7.1 0-13.9-1.2-20.3-3.3c-5.5-1.8-11.9 1.6-11.7 7.4c.3 6.9 1.3 13.8 3.2 20.7c13.7 51.2 66.4 81.6 117.6 67.9s81.6-66.4 67.9-117.6c-11.1-41.5-47.8-69.4-88.6-71.1c-5.8-.2-9.2 6.1-7.4 11.7c2.1 6.4 3.3 13.2 3.3 20.3z" />
                </svg>
            </a>
        </li>

        <li class="nav-item">
            <a href="{% url 'account:view_past_timesheets' %}" class="nav-link">
                <span class="link-text">TimeSheet History</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                    <path
                        d="M75 75L41 41C25.9 25.9 0 36.6 0 57.9V168c0 13.3 10.7 24 24 24H134.1c21.4 0 32.1-25.9 17-41l-30.8-30.8C155 85.5 203 64 256 64c106 0 192 86 192 192s-86 192-192 192c-40.8 0-78.6-12.7-109.7-34.4c-14.5-10.1-34.4-6.6-44.6 7.9s-6.6 34.4 7.9 44.6C151.2 495 201.7 512 256 512c141.4 0 256-114.6 256-256S397.4 0 256 0C185.3 0 121.3 28.7 75 75zm181 53c-13.3 0-24 10.7-24 24V256c0 6.4 2.5 12.5 7 17l72 72c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-65-65V152c0-13.3-10.7-24-24-24z" />
                </svg>
            </a>
        </li>

    </ul>
</nav>

<body>
    <div id="clocks">
        <h2>Date: {{ current_day }}</h2> 
        <h3>Clocks</h3>
        <table>
            <tr>
                <th>Time In</th>
                <th>Time Out</th> 
            </tr>
            {% for timesheet in todays_timesheets %}
            <tr>
                <td>{{ timesheet.start_time|date:"H:i" }}</td>
                <td>
                    {% if timesheet.end_time %}
                        {{ timesheet.end_time|date:"H:i" }}
                    {% else %}
                        Pending
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="2">No entries for today.</td> 
            </tr>
            {% endfor %}
        </table>
        <h3>Status</h3>
    <p>Pending</p>
    <h3>Total</h3>
    <p>{{ total_hours }} hours</p>
</div>
    

</body>

</html>